#!/bin/bash

##
# The MIT License (MIT)
# 
# Copyright (c) 2024 Jacky Xie
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
##


# it has the following capabilities
# 1. [esc] to cancel search without navigating to home dir
# 2. -f to search for files and navigate to directory containing file
# 3. ability to pre-provide a search terms before entering fzf

# TODO ability to provide multiple search terms 
# TODO enforce flags must occur before search arguments


###########################
# copy the function below #
###########################

f() {
        search_type='d' # defaults to directory
        arg='' # defaults to all
        while [ $# -gt 0 ]; do
                if [ $1 == "-f" ]; then
                        search_type='f'
                else
                        arg+=$1
                fi
                shift
        done

        if [ $search_type == 'f' ]; then
                dirname=$(find * -type $search_type \
                                        ! -name '.git' \
                                        ! -name 'node_modules' \
                                | fzf --query="$arg" \
                                | xargs dirname) || return

        else
                dirname=$(find * -type $search_type \
                                        ! -name '.git'\
                                        ! -name 'node_modules' \
                                | fzf --query="$arg" ) || return
        fi
        cd $dirname
}

######################
# end function block #
######################

#############
# executing #
#############
f $@